name: test suite
on:
  push:
    branches-ignore:
        - "gh-readonly-queue/**"
  pull_request:
  merge_group:

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master # avoid the tag here to prevent dependabot from updating it
        with:
          toolchain: "1.82"
      - run: cargo test --all-targets --features tokio
      - run: cargo test --all-targets --features futures

  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master # avoid the tag here to prevent dependabot from updating it
        with:
          toolchain: "1.82"
          components: rustfmt
      - run: cargo fmt --all --check

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master # avoid the tag here to prevent dependabot from updating it
        with:
          toolchain: "1.82"
          components: clippy
      - run: cargo clippy --features tokio -- -D warnings
      - run: cargo clippy --features futures -- -D warnings

  allgreen:
    if: always()
    needs:
      - test
      - fmt
      - clippy
    runs-on: Ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
